# Generated by Django 6.0.5 on 2026-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('laptop', 'Laptop')], default='mobile', max_length=20),
        ),
    ]
